# Generated by Django 5.0.14 on 2026-07-16 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('chat', 'Chat'), ('summarise', 'Summarise'), ('quiz_gen', 'Quiz Generation')], max_length=20)),
                ('messages_json', models.JSONField(blank=True, null=True)),
                ('input_file_url', models.TextField(blank=True, null=True)),
                ('summary_output', models.TextField(blank=True, null=True)),
                ('explanation_output', models.TextField(blank=True, null=True)),
                ('language_used', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_sessions',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('question_bank', 'Question Bank')], max_length=20)),
                ('total_questions', models.SmallIntegerField()),
                ('correct_answers', models.SmallIntegerField()),
                ('score_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('answers_json', models.JSONField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('ai_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_learning.aisession')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_results',
            },
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', 'created_at'], name='ai_sessions_user_id_9f7a2b_idx'),
        ),
    ]
