# Generated by Django 5.0.14 on 2026-07-16 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('exam_type', models.CharField(choices=[('GCE_OL', 'GCE O/L'), ('GCE_AL', 'GCE A/L'), ('BAC_A', 'BAC A'), ('BAC_C', 'BAC C'), ('BAC_D', 'BAC D'), ('BAC_E', 'BAC E'), ('BAC_TECH', 'BAC Technique'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('HND', 'HND'), ('CEP', 'CEP')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5)),
                ('pdf_url', models.TextField()),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('exam_type', models.CharField(choices=[('GCE_OL', 'GCE O/L'), ('GCE_AL', 'GCE A/L'), ('BAC_A', 'BAC A'), ('BAC_C', 'BAC C'), ('BAC_D', 'BAC D'), ('BAC_E', 'BAC E'), ('BAC_TECH', 'BAC Technique'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire'), ('HND', 'HND'), ('CEP', 'CEP')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('specialty', models.CharField(blank=True, max_length=100)),
                ('year', models.SmallIntegerField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('both', 'Both')], max_length=10)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('file_size_kb', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=5)),
                ('is_public', models.BooleanField(default=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.note')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.question')),
            ],
            options={
                'db_table': 'download_logs',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('question', 'Question'), ('note', 'Note')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.note')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.question')),
            ],
            options={
                'db_table': 'bookmarks',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam_type', 'subject', 'year'], name='questions_exam_ty_bcc18d_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['school', 'is_public'], name='questions_school__aa522b_idx'),
        ),
    ]
