# Generated by Django 5.0.14 on 2026-08-04 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('abbreviation', models.CharField(max_length=20)),
                ('subsystem', models.CharField(choices=[('anglophone', 'Anglophone'), ('francophone', 'Francophone')], max_length=20)),
                ('exam_levels', models.JSONField(default=list)),
                ('is_general', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'db_table': 'specialties',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='specialty',
            constraint=models.UniqueConstraint(fields=('name', 'subsystem'), name='uniq_specialty_name_subsystem'),
        ),
    ]
