# Generated by Django 5.0.14 on 2026-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_specialty_specialty_uniq_specialty_name_subsystem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='specialty',
            name='uniq_specialty_name_subsystem',
        ),
        migrations.AddField(
            model_name='specialty',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='specialty',
            name='code',
            # The catalogue table is empty at this point, so the one-off default
            # is only needed to satisfy the NOT NULL add; it is not kept.
            field=models.SlugField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='exam_type',
            field=models.CharField(choices=[('GCE_OL', 'GCE O/L'), ('GCE_AL', 'GCE A/L'), ('GCE_TVE_OL', 'GCE TVE Intermediate Level'), ('GCE_TVE_AL', 'GCE TVE Advanced Level'), ('HND', 'HND'), ('CEP', 'CEP'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire Général'), ('BAC_GEN', 'Baccalauréat Général'), ('CAP', 'CAP'), ('PROBATOIRE_TECH', 'Probatoire Technique / STT'), ('BAC_TECH', 'Baccalauréat Technique & BT'), ('BTS', 'BTS'), ('CONCOURS_ENSP', 'Concours ENSP / Polytechnique'), ('CONCOURS_FMSB', 'Concours FMSB / CUSS'), ('CONCOURS_ENS', 'Concours ENS'), ('CONCOURS_ENAM', 'Concours ENAM'), ('CONCOURS_SANTE', 'Concours Santé Publique'), ('BAC_A', 'BAC A (legacy)'), ('BAC_C', 'BAC C (legacy)'), ('BAC_D', 'BAC D (legacy)'), ('BAC_E', 'BAC E (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam_type',
            field=models.CharField(choices=[('GCE_OL', 'GCE O/L'), ('GCE_AL', 'GCE A/L'), ('GCE_TVE_OL', 'GCE TVE Intermediate Level'), ('GCE_TVE_AL', 'GCE TVE Advanced Level'), ('HND', 'HND'), ('CEP', 'CEP'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire Général'), ('BAC_GEN', 'Baccalauréat Général'), ('CAP', 'CAP'), ('PROBATOIRE_TECH', 'Probatoire Technique / STT'), ('BAC_TECH', 'Baccalauréat Technique & BT'), ('BTS', 'BTS'), ('CONCOURS_ENSP', 'Concours ENSP / Polytechnique'), ('CONCOURS_FMSB', 'Concours FMSB / CUSS'), ('CONCOURS_ENS', 'Concours ENS'), ('CONCOURS_ENAM', 'Concours ENAM'), ('CONCOURS_SANTE', 'Concours Santé Publique'), ('BAC_A', 'BAC A (legacy)'), ('BAC_C', 'BAC C (legacy)'), ('BAC_D', 'BAC D (legacy)'), ('BAC_E', 'BAC E (legacy)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='subsystem',
            field=models.CharField(choices=[('anglophone', 'Anglophone'), ('francophone', 'Francophone'), ('bilingual', 'Bilingual / both subsystems')], max_length=20),
        ),
    ]
