# Generated by Django 5.0.14 on 2026-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_specialty_uniq_specialty_name_subsystem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='notes', to='content.specialty'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='questions', to='content.specialty'),
        ),
    ]
