# Generated by Django 5.0.14 on 2026-08-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('confessional', 'Confessional')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='subsystem',
            field=models.CharField(choices=[('anglophone', 'Anglophone'), ('francophone', 'Francophone'), ('bilingual', 'Bilingual')], default='bilingual', max_length=20),
        ),
    ]
