# Generated by Django 5.0.14 on 2026-08-04 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_school_type_school_subsystem'),
        ('content', '0002_specialty_specialty_uniq_specialty_name_subsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='content.specialty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
