# Generated by Django 5.0.14 on 2026-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_specialty_ref_alter_user_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exam_level',
            field=models.CharField(blank=True, choices=[('GCE_OL', 'GCE O/L'), ('GCE_AL', 'GCE A/L'), ('GCE_TVE_OL', 'GCE TVE Intermediate Level'), ('GCE_TVE_AL', 'GCE TVE Advanced Level'), ('HND', 'HND'), ('CEP', 'CEP'), ('BEPC', 'BEPC'), ('PROBATOIRE', 'Probatoire Général'), ('BAC_GEN', 'Baccalauréat Général'), ('CAP', 'CAP'), ('PROBATOIRE_TECH', 'Probatoire Technique / STT'), ('BAC_TECH', 'Baccalauréat Technique & BT'), ('BTS', 'BTS'), ('CONCOURS_ENSP', 'Concours ENSP / Polytechnique'), ('CONCOURS_FMSB', 'Concours FMSB / CUSS'), ('CONCOURS_ENS', 'Concours ENS'), ('CONCOURS_ENAM', 'Concours ENAM'), ('CONCOURS_SANTE', 'Concours Santé Publique'), ('BAC_A', 'BAC A (legacy)'), ('BAC_C', 'BAC C (legacy)'), ('BAC_D', 'BAC D (legacy)'), ('BAC_E', 'BAC E (legacy)')], max_length=20, null=True),
        ),
    ]
