# Generated by Django 5.0.14 on 2026-08-05 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_note_is_general_note_specialties_question_is_general_and_more'),
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='scope',
            field=models.CharField(choices=[('general', 'General'), ('exam', 'Exam'), ('specialty', 'Specialty')], default='general', max_length=12),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='scope_exam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='scope_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='content.specialty'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['scope', 'scope_exam'], name='forum_posts_scope_1e8426_idx'),
        ),
    ]
